title: The Cherry Picker's Guide
description: This is a blog for developers to learn best practices for selecting efficient code, with real-world examples and tips.
theme: just-the-docs
url: https://dylanmsk.github.io/


color_scheme: custom


# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout